id: PB6381FFB
initial_creation_type: ocr
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA00EGS1017422
  instance_id: http://purl.bdrc.io/resource/IE00EGS1017422
  collection_id: http://purl.bdrc.io/resource/PR0ET009
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - དྲི་བཟང་ཐུལ་བའི་སྨན་ལྗོངས།
  alt_title:
    zh-latn-pinyin-x-ndia:
    - xiang yi bai cao yuan
  author: None
  publisher: UCB-OCR
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    c2e1f2d8b87a44d8b1587e00f1147390:
      title: པོད ༡་དྲི་བཟང་ཐུལ་བའི་སྨན་ལྗོངས
      volume_number: 1
      base_file: UT00EGS1017422_I1PD28032_0000.txt
      reference: http://purl.bdrc.io/resource/VL6C203A62F05FBD14
      image_group: I1PD28032
      quality: Low
  reproductionOf:
  - http://purl.bdrc.io/resource/MW00EGS1017422
  - http://purl.bdrc.io/resource/W00EGS1017422
  ocr_software: Namsel
created_at: '2021-12-22T10:14:06.434031'
last_modified_at: '2021-12-22T10:14:06.434036'
statistics:
  total_words: 88920
  total_non_words: 13144
quality:
  non_words_ratio: 0.15
